### Theory

Numpy (Numerical Python) is a scientific computing library. It uses arrays to perform calculations and plot graphs. The NumPy is maintained by a different community. They maintain different versions. Each version comes with better optimization or new features

### Further Reading : 
[Book](https://jakevdp.github.io/PythonDataScienceHandbook/)

[Stanford Course](https://cs231n.github.io/python-numpy-tutorial/)

[Exercises](https://github.com/rougier/numpy-100)

### Importing the Modules

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Basics

In [5]:
print(np.__version__) # Prints the current version of numpy being used
print(np.show_config()) # Prints other packages the current version of numpy depends upon
# Many of these libraries are written in c (Eg : openblas)

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/daver/Anaconda_Files/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/daver/Anaconda_Files/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/daver/Anaconda_Files/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/daver/Anaconda_Files/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/daver/Anaconda_Files/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/daver/Anaconda_Files/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/daver/Anaconda_Files/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/daver/Anaconda_Fil

### Creating a NumPy array
##### <i>We mostly use numerical arrays only</i>
NumPy arrays are not strictly homogenous (Objects), but they are ususally used only homogenously

In [16]:
# Converting List to an array :
a = np.array([1, 2, 3])
print(type(a)) # <class 'numpy.ndarray'>
print(a.shape) # (3,) as it is 1D with 3 elements and tuples are ended with ,

print(a[0], a[1], a[2]) # Accessing similar to list
a[0] = 5 # Replaces like list


# Nested list or Rank 2 array or 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape) #(2, 3) or 2 rows and 3 cols [Row is refered to as first dimension and column the second]
# First element becomes first row and second element becomes second row
print(b[0, 0], b[0][1])


# 3D and 4D arrays are used in Deep Learning


# If you provide the first as 3 element and the second as 2 element, then numpy return VisibleDeprecationWarning
l = [[1, 2, 3], [4, 5, 6]]
ary2d = np.array(l)
print(ary2d)
'''
[[1 2 3]
 [4 5 6]]
'''

print(ary2d.dtype) # int64

float_32_array = ary2d.astype(np.float32) # Converts to float with 32 memory bits. This is NOT DONE IN PLACE
# OR
ary2d = ary2d.astype(np.float32) # Converts then stores it in the same variable without creating copy


<class 'numpy.ndarray'>
(3,)
1 2 3
(2, 3)
1 2
[[1 2 3]
 [4 5 6]]
int64


### Generating Numbers

In [31]:
# Create sequencial values from 10 to 49
z = np.arange(10, 50)

# Print first and last 10 elements : 
print(z[:10]) # All slicing operations valid
print(z[-10:]) 


# Print in Reverse:
print(z[::-1])


a = np.zeros((2, 2)) # 2x2 Matrix with all entries initialized to 0. Default type is float
b = np.ones((1, 2)) # One row and two columns with ones as values

c = np.full((2, 3), 7) # 2x3 array with all elements as 7

d = np.eye(4) # Creates a 4x4 Identity matrix (Always square)
# d = np.identity(4)


# GENERATING RANDOM VALUES
'''
It is not possible to make true randomness in computers. We use Recursive Modulo Arithmetic Operation (Psuedo Random Number Theory)
We can specify a starting point and it sequencially generates random numbers from there

Seed the random function with an integer for repeatability
If we seed, we get the same set of random numbers for the matrix
'''

np.random.seed(42) # Can be any int, 42 is standard
x1 = np.random.randint(10, size = 6) # 1D Array with 6 members and upper bound of 9
x2 = np.random.randint(10, size = (3, 4)) # 2D array
'''
To find the Documentation : 
np.random.randint?? only works for jupyter or google collab
help(np.random.randint)

==>
randint(low, high=None, size=None, dtype=int)
'''

x3 = np.random.randint(10, size = (3, 4, 5)) # 3D Array (understand that there 3 4x5 dimensionals arrays)

'''
Generic Names 
1D : Row or Column Vector
2D and 3D : Arrays
4D and Above : Tensors
'''

print(x3.ndim) # Returns the dimension of the array
print(x3.shape) # Returns the dimensions
print(x3.size) # Returns the number of elements (Multiply the elements of shape)
print(x3.dtype) # int64
print(x3.itemsize) # Returns the size of each element
print(x3.itemsize * x3.size) # Returns the size of the array
print(x3.nbytes) # Same as above


[10 11 12 13 14 15 16 17 18 19]
[40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
3
(3, 4, 5)
60
int64
8
480
480


### Slicing Operations

In [32]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Sliced result is actually a pointer to the original array. Modifying the slice will modify the original array

# Slices the first two rows and columns one and two. Returns subdimension (2, 2)
b = a[:2, 1:3]
print(a[0, 1]) # 2

b[0, 0] = 77 # Will modify a[0, 1]

b2 = a[:2, 1:3].copy() # Will create a copy so no modifications will reflect
# np.copy(a[:2, 1:3])


### Array Mathematics

In [3]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

# Elementwise Sum : 
print(x + y)
print(np.add(x, y))

# Elementwise Difference
print(x - y)
print(np.subtract(x, y))

# Elementwise Sum
print(x * y)
print(np.multiply(x, y))

# Elementwise Division
print(x - y)
print(np.divide(x, y))

# Elementwise Square root
print(np.sqrt(x, y))


# Array transpose
print(x.T)
'''
Doesnt change anything for 1D arrays
Instead, do : 
x1 = x.reshape((1, 3))
print(x1.shape)
print(x1.T)
'''

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[-4. -4.]
 [-4. -4.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1. 3.]
 [2. 4.]]


'\nDoesnt change anything for 1D arrays\nInstead, do : \nx1 = x.reshape((1, 3))\nprint(x1.shape)\nprint(x1.T)\n'

### Array Broadcasting

In [4]:
# Add the vector V to each row of the matrix x and store in y
x = np.array([[4, 5, 6], [7, 8, 9]])
v = np.array([1, 2, 3])
y = x + v # Adds v to each row of x using broadcasting
# [1, 2, 3] will be broadcased to a second row and both will be added


print(np.arange(3) + 5)
print(np.ones((3, 3)) + np.arange(3))
print(np.arange(3).reshape((3, 1)) + np.arange(3))

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
